### ISSUE TITLE
Document some recommended mailing list filters

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2714] opened 2018-09-26 16:57 UTC
People who join k8s have to follow a bunch of lists, Tim has some filters here he uses: 

https://groups.google.com/forum/#!topic/kubernetes-dev/5qU8irU7_tE

Ideally make a page that lists these (and think of some others, get feedback) so that we can share this with new contributors and we can maintain it over time. We also need to link to it from the contributor cheat sheet. 

/good-first-issue
/sig contributor-experience

**Comment by nikhita** [comment] 2018-09-26 17:51
@castrojo this looks like a dupe of https://github.com/kubernetes/community/issues/1724

**Comment by parispittman** [comment] 2018-10-15 11:07
closing in favor of #1724 

/close

**Closed by parispittman** 2018-10-15 11:07 UTC
Labels: good first issue, help wanted, sig/contributor-experience
