### ISSUE TITLE
KubeCon Contributor Summit NA 2024 - Team Staffing

### ISSUE THREAD

**Issue by mfahlandt** [kubernetes/community#7854] opened 2024-04-29 15:45 UTC
The 2024 NA Contributor Summit in Salt Lake City will need staffing for its roles and shadows. The Contributor Summit date and location is to be determined. 
Planning meetings occur on Mondays at [9 AM Pacific/11 AM Central](https://dateful.com/convert/pst-pdt-pacific-time?t=09). (Sorry about this again, but other times are hardly working, we maybe can move it to  [10 AM Pacific/12 AM Central](https://dateful.com/convert/pst-pdt-pacific-time?t=10). 

Event Leads will be @mfahlandt and @stmcginnis as shadow.
The emeritus advisor is @salaxander 

We will also need shadows that could potentially take on leading those roles in the future. Roles and shadows will be listed below when they are filled out. With limited exception, shadows must have Kubernetes org membership. Shadows will be accepted at the discretion of the lead.

To clarify roles and responsibilities, we are adding a role of "Volunteer" under each area. The Shadow bears expectations to lead one of the events-team roles in an upcoming summit and to handle all lead related activities in the absence of the Lead. It may be helpful to think of the Shadow role as an understudy position. Volunteers are helpers that may be assigned tasks from the Lead. Shadows and Volunteers, with limited exception, must be members of the Kubernetes GitHub organization. Leads are still responsible for accepting shadows and volunteers for their area. Volunteers, please communicate your desire to be a Shadow to the Lead of your area. Leads will inform me of their Shadows and I will update the issue.

We have a strong preference that participants as Leads, Shadows, and Volunteers be present at the Contributor Summit to help on site. This does not mean you cannot help virtually. There will be opportunities and we encourage you to come to the planning meetings in order to find virtual opportunities.
Thank you for your willingness to help out. We could not hold these events without you.

[Registration](https://github.com/kubernetes/community/blob/master/events/events-team/registration/README.md)
Lead: @savitharaghunathan 
Shadow: @salaxander @sreeram-venkitesh @JamesLaverack 
Volunteers: 
Emeritus Lead: @reylejano 

[Content](https://github.com/kubernetes/community/blob/master/events/events-team/content/README.md)
Lead: @nitishfy 
Shadow:   @krol3 @hakman @jeremyrickard
Volunteers:
Emeritus Advisor: @fykaa 

[Comms](https://github.com/kubernetes/community/blob/master/events/events-team/marketing/README.md)
Lead: @kaslin 
Shadow:  @sandipanpanda, @ArvindParekh, @fykaa, @rayandas, and @sandeepkanabar 
Volunteers: 
Website: @mfahlandt 

[Awards](https://github.com/kubernetes/community/blob/master/events/awards/playbook.md)
Lead: @tokt 
Shadow:  @lauralorenz 

Social Event (Required onsite in Salt Lake City)
Lead: @salaxander
Shadow: @drewhagen
Volunteers:

[Day-of Operations (Required onsite in Salt Lake City)](https://github.com/kubernetes/community/tree/master/events/events-team/operations)
Lead: @jberkus 
Shadow: @reylejano, @cpanato 
Volunteers: 
Emeritus Advisor: 

[SIG Meet & Greet (Preferred onsite in Salt Lake City)](https://github.com/kubernetes/community/blob/master/events/events-team/content/meet-and-greet.md)
Lead: @kaslin 
Shadow:  @reylejano
Volunteers: 
Emeritus Advisor: 

Floating Volunteers (Preferred onsite in Salt Lake City)

/assign @mfahlandt @stmcginnis
/sig contributor-experience
/area contributor-summit
/area na-summit

**Comment by salaxander** [comment] 2024-04-29 15:59
I would love to shadow registration :)

**Comment by JamesLaverack** [comment] 2024-04-29 16:11
👋 I'd love to shadow, either registration or comms ideally. I won't be on-site at SLC.

**Comment by jberkus** [comment] 2024-04-30 00:37
I'm available for either Awards or Operations.  I can also take a specific task from Operations.

**Comment by savitharaghunathan** [comment] 2024-04-30 13:18
I would love to shadow comms or awards! Unsure if I will be onsite this time as well.

**Comment by rayandas** [comment] 2024-04-30 14:12
Hey everyone 👋 I’d love to shadow/volunteer for comms.

**Comment by krol3** [comment] 2024-04-30 16:39
Hey everyone 👋 , I would love to do a shadow registration :), I could help on site in the days of NA Contributor Summit in Salt Lake City

**Comment by nitishfy** [comment] 2024-04-30 16:49
I previously shadowed for the Content Team and this time I'd like to shadow for the comms team.

**Comment by reylejano** [comment] 2024-04-30 17:01
I would love to shadow the Meet and Greet or Content

**Comment by sreeram-venkitesh** [comment] 2024-04-30 18:02
I would love to shadow the registrations team this time :)

**Comment by jeremyrickard** [comment] 2024-05-01 01:31
Hello! Long time attendee, would love to volunteer and support this.

Would love to shadow awards, content, or social event, but would be happy to help out anywhere where I could be useful and help make the event successful! 

I plan to be onsite.

**Comment by fykaa** [comment] 2024-05-01 08:18
I would love to be the Emeritus Advisor for content and can lead it too if none of the prev shadows want to.

**Comment by hakman** [comment] 2024-05-01 09:03
Hey 👋 , I would love to shadow contend or awards. I am not 100% sure that I will be onsite this time.

**Comment by drmorr0** [comment] 2024-05-01 15:50
I'm happy to volunteer, but probably not shadow or lead (this time!)

**Comment by reylejano** [comment] 2024-05-01 20:45
I can also be the Emeritus Advisor for Registration

**Comment by ArvindParekh** [comment] 2024-05-03 04:43
Hi everyone! I've been a regular attendee of the SIG-ContribEx meetings. I'm eager to take on more responsibility and I would love to shadow Comms and help out. I'd also be interested in shadowing Content.

**Comment by savitharaghunathan** [comment] 2024-05-06 16:14
I can lead Registration team :)

**Comment by kaslin** [comment] 2024-05-06 16:20
I volunteer as lead for Meet & Greet and Comms

**Comment by tokt** [comment] 2024-05-06 16:22
Will be happy to lead Awards and/or help in any other area.

**Comment by mfahlandt** [comment] 2024-05-06 19:42
Most of the Lead roles have been staffed, please consider the volunteered shadows and confirm them. 

We are still open for additional Shadows & Volunteers and are looking for a Social Event Lead

**Comment by savitharaghunathan** [comment] 2024-05-08 15:06
@JamesLaverack @nitishfy - I see you have expressed interest in multiple shadow roles. Do you have a preference?

**Comment by nitishfy** [comment] 2024-05-08 15:16
> @JamesLaverack @nitishfy - I see you have expressed interest in multiple shadow roles. Do you have a preference?

Hey Savitha, I'm already volunteering as a Content lead this time, That being said, I might not have enough bandwidth to shadow registration this time :)

**Comment by nimbinatus** [comment] 2024-05-08 16:11
I can't confirm that I will be in person yet, but once I can confirm later this year, I will do what I can to help.

**Comment by JamesLaverack** [comment] 2024-05-09 09:57
> I see you have expressed interest in multiple shadow roles. Do you have a preference?

@savitharaghunathan Minor preference for Registration, but I'm fine with either if that's better for the team distribution. :)

**Comment by sandipanpanda** [comment] 2024-05-10 16:42
I would like to shadow Comms this time.

**Comment by savitharaghunathan** [comment] 2024-05-13 11:34
I would like to confirm @salaxander @sreeram-venkitesh @JamesLaverack as shadows for Registration 🎉

**Comment by nitishfy** [comment] 2024-05-13 11:47
Confirming @krol3 and @hakman  as the Content Shadows🎉

**Comment by reylejano** [comment] 2024-05-14 03:30
I would like to shadow Day of Ops and SIG Meet & Greet

**Comment by jberkus** [comment] 2024-05-14 20:28
Rey: would be happy to have you as shadow/staff.

**Comment by kaslin** [comment] 2024-05-22 23:29
Confirming @reylejano as Meet & Greet shadow.

**Comment by lauralorenz** [comment] 2024-05-29 18:21
I can't guarantee I will be in person yet but I'd like to help. I've previously shadowed Content and happy to shadow or volunteer for that team again, or shadow/volunteer for Comms or Awards as they seem like a good fit for having a good amount of pre-con offsite stuff to do.

**Comment by tokt** [comment] 2024-05-30 03:23
confirming @lauralorenz as a shadow for Awards (and really hope you'll make it!)

**Comment by cpanato** [comment] 2024-05-30 19:07
I would like to join the day operations if have space for me :)

**Comment by kaslin** [comment] 2024-05-30 20:14
Confirming @sandipanpanda, @ArvindParekh, @fykaa, @rayandas, and @sandeepkanabar as comms shadows.

**Comment by jberkus** [comment] 2024-05-30 20:36
Hey, @cpanato Ops needs lots of folks, like always!  Got you on the list.  Unless you were asking to co-shadow?

**Comment by todaywasawesome** [comment] 2024-05-30 23:39
I'm onsite in SLC and can help with the social event.

**Comment by mfahlandt** [comment] 2024-06-03 15:55
> I'm onsite in SLC and can help with the social event.

Hey Dan, this is really great to hear. I saw, you are not part of the @Kubernetes or Kubernetes-Sig Org. This is also a requirement for joining the summit. Are you currently working towards an Org membership?  We can discuss this in the Kubernetes Slack just Ping me @mfahlandt there :)

**Comment by cpanato** [comment] 2024-06-04 07:36
> Hey, @cpanato Ops needs lots of folks, like always! Got you on the list. Unless you were asking to co-shadow?

just hands on help :)

**Comment by schristoff** [comment] 2024-06-07 04:13
I'll be onsite in SLC, happy to help with Day of Operaotrs, SIG Meet & Greet, or anywhere else I can help. :)

**Comment by satyampsoni** [comment] 2024-06-14 06:49
I am not sure if it is too late, I would like to shadow for registration or content, if there is space left.

**Comment by RA489** [comment] 2024-07-01 05:10
I was Shadow for SIG M &G for KubeCon EU 2024. Would love to shadow/volunteer this time too.

**Comment by salaxander** [comment] 2024-07-08 15:51
Confirming @drewhagen as a shadow for social. @todaywasawesome, still interested in also shadowing for social event?

**Comment by mehabhalodiya** [comment] 2024-09-05 09:10
Would like to shadow for the Awards or anywhere else I can help (if you are still considering). I will be there in person.

**Comment by henryfish12** [comment] 2024-10-08 17:53
Looking forward to contributing to the 2024 NA Contributor Summit; I'll attend the planning meetings and keep an eye out for roles and shadows.

**Comment by sandeepkanabar** [comment] 2024-10-08 20:12
@mehabhalodiya @henryfish12 - since you expressed interest in helping out with KCSNA, @jberkus is looking for OPS volunteers. Feel free to add your name to this [sheet](https://docs.google.com/spreadsheets/d/1oTPG3raG9xK8DPuicC3b8cBEAqRIyPnVroDQaTu40SI/edit?gid=2080248557).

Tip: If you put yourself on the schedule, for at least 2 shifts in any role(s), by October 9th, Josh will be able to order volunteer apparel for you with your Github handle embroidered on it :)

**Closed** 2024-12-16 23:37 UTC
Labels: sig/contributor-experience, area/contributor-summit, area/na-summit
