### ISSUE TITLE
Fill in latest Sig-AWS subprojects to README

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes/community#2507] opened 2018-08-09 19:45 UTC
Was just at the community meeting where Nishi Davidson went over some great new [subprojects](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit?disco=AAAACFpCSJQ) under sig-aws. These should be added to the readme (I think @spiffxp mentioned how sig leads can do this) with proper links to owners etc..

/sig aws

**Comment by spiffxp** [comment] 2018-08-10 23:48
/close 
Duplicate of https://github.com/kubernetes/community/issues/2474

**Closed by spiffxp** 2018-08-10 23:48 UTC
Labels: sig/aws
