### ISSUE TITLE
KEP numbers are not unique

### ISSUE THREAD

**Issue by justinsb** [kubernetes/community#2834] opened 2018-10-22 19:26 UTC
There are 2 KEP 30s:

https://github.com/kubernetes/community/blob/master/keps/sig-api-machinery/0030-storage-migration.md

https://github.com/kubernetes/community/blob/master/keps/sig-network/0030-nodelocal-dns-cache.md

I think there are also two KEP 28s, two KEP 18s, three KEP 15s.

I'm guessing that rebase-needed detection doesn't work the way we think it does...

**Comment by justaugustus** [comment] 2018-10-24 10:49
Closing this as a duplicate of https://github.com/kubernetes/community/issues/2245.

/close

**Closed by justaugustus** 2018-10-24 10:49 UTC
Labels: kind/cleanup, kind/kep, sig/architecture
