### ISSUE TITLE
[Discussion] Remove language that might come across inconsiderate

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/community#4399] opened 2020-01-14 17:34 UTC
Inspiration for this comes from other open-source projects: https://github.com/facebook/jest/commit/59f6e3fd3fe6b502100a9c91ea22e91fe554136b and https://github.com/pivotal/docs-concourse-pcf/pull/22.

A quick and very superficial search brings back a pretty big number of occurrences of just/simple/simply/of course etc. - however, other than that, I haven't thoroughly looked into how frequently they pop up, and I haven't done any work whatsoever to gauge what the impact might be at the moment.

For now, I'm curious to hear what feedback or other input folks have on this, and we can talk complexity and next steps if we think it makes sense in principle.

**Comment by mariantalla** [comment] 2020-01-14 17:35
/sig contributor-experience
/sig docs
seem like the most appropriate ones 🤔

**Comment by parispittman** [comment] 2020-01-14 17:36
+1, on board. very considerate discussion topic ;) thanks for bringing this up @mariantalla

**Comment by mariantalla** [comment] 2020-01-14 17:42
I see what you did there 🙃

**Comment by dims** [comment] 2020-01-15 01:31
LOL +1 :)

**Comment by mrbobbytables** [comment] 2020-01-15 12:44
+1 As well. Outside of being potentially inconsiderate, omitting unnecessary adverbs improves readability and helps non-native english speakers.

/cc @zacharysarah @jimangel @Bradamant3 
For comments from docs 👍

**Comment by zacharysarah** [comment] 2020-01-15 14:47
+1

Can we get rid of `master` and `slave` while we’re at it?

**Comment by jimangel** [comment] 2020-01-15 14:54
BIG +1! Thanks @mariantalla!

**Comment by parispittman** [comment] 2020-01-15 14:58
I don't think you'll see many folks disagree on principle. What about putting a plan together for the /community repo as a small(er) playground to test?  If you want to recruit some folks to help (with plan or execution), mail this issue link to the contribex mailing list.

**Comment by tmart333** [comment] 2020-01-15 18:23
@mariantalla as a novice to github and a non-coder, I'd love to be involved in this. I subscribed to this issue... is there something else I should do to track this? :)

**Comment by mbbroberg** [comment] 2020-01-15 18:27
Hey @mariantalla :wave:, ping me if I can help scope how to tackle this!

**Comment by cblecker** [comment] 2020-01-15 18:43
- We can use hound to help us find occurrences of a word across all our repos: https://cs.k8s.io/?q=just&i=fosho&files=%5C.md
- We have both a contribex and a sig-docs style guide.. if we want to remove certain language, we should update these style guides and notify k-dev

**Comment by mbbroberg** [comment] 2020-02-14 16:57
Jumping back in (thanks for the nudge @mariantalla!). Thinking process-wise, I could see this issue being reframed as a meta issue with the following checklist items:

- [ ] use hound to find instances of undesirable language
- [ ] update sig-docs style guide to advise on language
- [ ] categorize these instances to make a set of issues people can fix  
- [ ] notify k-dev of these updates and invite to edit 

I'll be hanging out in `#sig-contribex` on Slack if you want to through through it more in real-time. Alternatively, it might be helpful to spin up a `#temp-inclusive-language` as a temporary channel to work through the problem. 

Throwing this out here to start and happy to see where we want to run with it 🏃🏃

**Comment by mbbroberg** [comment] 2020-02-14 17:04
Looking through hound, I see a ton of _just_ instances alone. They are, thankfully, not in a ton of repositories, so that could be the most natural separation for issues. For instance "Remove instances of uninclusive language from $REPO" as a template and that outlines the style guide updates.

**Comment by celestehorgan** [comment] 2020-08-05 21:21
/wg naming

Duplicate/overlapping issue: https://github.com/kubernetes/website/issues/17070

**Comment by mrbobbytables** [comment] 2020-10-07 17:04
@celestehorgan do you think we should close this issue and track in k/website or another issue?

**Comment by celestehorgan** [comment] 2020-10-13 16:53
@mrbobbytables The correct escalation for this issue (at this point) is to take this to the WG Naming mailing list and propose, for each term to replace, a replacement (or to remove the language entirely, as it were). 

I can take care of that and we can close this issue after?

/assign

**Comment by mrbobbytables** [comment] 2020-10-13 21:10
That sgtm! Thanks for taking point :)

**Comment by zacharysarah** [comment] 2020-11-05 00:19
Duplicate of https://github.com/kubernetes/website/issues/17070; I recommend closing this issue.

/close

**Closed** 2020-11-05 00:19 UTC
Labels: area/contributor-guide, sig/contributor-experience, sig/docs, wg/naming
